using System;
using System.IO;
using System.Text;

internal class UnityGeneratedCreatorCSharp : UnityGeneratedCreator
{
    private readonly string template = "\n// GENERATED BY UNITY\n// DO NOT MODIFY, THIS FILE WILL BE OVERWRITTEN DURING NEXT BUILD\nusing Windows.Graphics.Display;\nusing Windows.UI.ViewManagement;\n\nnamespace Unity\n{\n    public class UnityGenerated\n    {\n        public static void SetupDisplay()\n        {\n            $SetupDisplay$\n        }\n    }\n}\n    ";

    internal override string[] Create(string directory)
    {
        string[] strArray = new string[] { "UnityGenerated.cs" };
        StringBuilder builder = new StringBuilder(this.template);
        string displaySetupCode = base.GetDisplaySetupCode();
        builder.Replace("$SetupDisplay$", displaySetupCode);
        File.WriteAllText(Path.Combine(directory, strArray[0]), builder.ToString());
        return strArray;
    }

    protected override string IndentCodeLine() => 
        "\t\t\t";
}

